site_name: My Homelab & Knowledge Blog
site_description: Personal knowledge base, homelab documentation and blog
site_url: https://example.com


theme:
  name: material
  highlightjs: false

  features:
    - navigation.indexes
    - blog
    - navigation.tabs
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - navigation.top
    - toc.integrate
    - navigation.sections
    - navigation.expand
    - content.tooltips
    - navigation.instant
    - palette.toggle  # Enables the dark mode toggle
    - palette
  palette:
      - scheme: default
        primary: blue grey
        accent: teal
        toggle:
          icon: material/weather-night
          name: Switch to dark mode
      - scheme: slate
        primary: blue
        accent: light green
        toggle:
          icon: material/weather-sunny
          name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: false
      linenums: false
      use_pygments: true
      guess_lang: false
  - pymdownx.snippets
  - pymdownx.escapeall
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      custom_checkbox: true


plugins:
  - search
  - blog:
      blog_toc: true
      archive_date_format: MMMM yyyy
      categories_allowed:
          - HomeLabs
          - News
          - lifestyle
      pagination_per_page: 5
      archive_pagination_per_page: 10
      categories_pagination_per_page: 10
  - tags:
        tags_file: blog/tags.md



extra_css:
  - stylesheets/extra.css


extra_javascript:
  - assets/js/strip-shell-prompts.js
  - https://cdnjs.cloudflare.com/ajax/libs/fontfaceobserver/2.1.0/fontfaceobserver.standalone.js
  

extra:
  font:
    text: Roboto
    code: Fira Code

nav:
  - Home: index.md
  - Blog:
      - Overview: blog/index.md
      - Tags: blog/tags.md
  - Homelabs:
      - Overview: Homelabs/index.md
      - AI: Homelabs/AI/index.md
      - Cybersecurity: Homelabs/Cybersecurity/index.md
      - Proxmox:
        - Overview: Homelabs/Proxmox/index.md
        - Hardware: Homelabs/Proxmox/hardware.md
        - Installation : Homelabs/Proxmox/proxmox-installation.md
        - GPU Passthrough  : Homelabs/Proxmox/GPU-passthrough.md
        - Services : 
          - Overview : Homelabs/Proxmox/services/index.md
          - Gitea:
              - Overview: Homelabs/Proxmox/services/Gitea/index.md
              - Installation: Homelabs/Proxmox/services/Gitea/installation.md
          - Docker-server:
              - Overview: services/Docker-server/index.md
              - Set-up: services/Docker-server/Set-up.md
              - portainer: services/Docker-server/portainer.md
      - Tags: Homelabs/tags.md
  - What's in My Labs : 
      - Services : 
          - Overview : services/index.md
          - Gitea:
              - Overview: services/Gitea/index.md
              - Installation & Setup: services/Gitea/installation.md
          - database:
              - Overview: services/database/index.md
              - Installation: services/database/installation.md
          - Docker-server:
              - Overview: services/Docker-server/index.md
              - Set-up: services/Docker-server/Set-up.md
          - Pi-hole:
              - Overview: services/Pi-hole/About.md
      - Security : 
          - Overview: security/index.md
          - SSL: security/ssl/ssl.md
          - Tunnel: security/tunnel/tunnel.md
      - Synchronization : 
          - Overview: Synchronization/index.md
          - rsync: Synchronization/rsync/index.md
          - syncthing: Synchronization/syncthing/index.md

  - Web Vulnerability: 
          - Overview: web-vulnerability/index.md
          - Prototype-pollution: web-vulnerability/prototype-pollution/Prototype-pollution.md
  - Cloudlabs : Cloudlabs/index.md
      



